#ifndef __ASCII_H
#define __ASCII_H


enum {
    ASCII_NULL_CHAR_CODE      = 0x00,
    ASCII_BKSPACE_CHAR_CODE   = 0x08,
    ASCII_NEWLINE_CHAR_CODE   = 0x0a,
    ASCII_CRETURN_CHAR_CODE   = 0x0d,
    ASCII_SPACE_CHAR_CODE     = 0x20,
    ASCII_PERCENT_CHAR_CODE   = 0x25,
};


#endif
